In [3]:
import numpy as np

In [4]:
a = np.array([[0.7 , 0.15, 0.15] ,
 [0.2 , 0.8 , 0.15] ,
 [0.1 , 0.05, 0.7 ]])

print(a)

[[0.7  0.15 0.15]
 [0.2  0.8  0.15]
 [0.1  0.05 0.7 ]]


In [5]:
n = (a.size) ** (.5)

In [6]:
n = int(n)

In [7]:
n

3

In [8]:
a[0,0]

0.7

In [9]:
for i in range(n):
    x= (a.transpose()[i].sum()).round(2)
    if x != 1:
        print ('Transition Matrix Values Must add up to 1')

In [10]:
a.transpose()

array([[0.7 , 0.2 , 0.1 ],
       [0.15, 0.8 , 0.05],
       [0.15, 0.15, 0.7 ]])

In [12]:
b = np.array([.15,.20,.65])

In [16]:
b = b.reshape(3,1)

In [21]:
b.sum()

1.0